### ISSUE TITLE
Read file problem

### ISSUE THREAD

**Issue by tattiyaS** [anapgh/pycefrl#4]
There are some problems occurred when I tried to run your code with repositories that have license. The screenshot of the terminal is attached as references. 

P.S. Please update your readme.md, I have some trouble follow your instructions.
![image](https://user-images.githubusercontent.com/46751639/122647221-1a1a6300-d15e-11eb-9c1d-3c08553f4b09.png)
![image](https://user-images.githubusercontent.com/46751639/122647229-26062500-d15e-11eb-9a17-90683b2e6c9f.png)

**Comment by anapgh** [comment]
Hi! Your error I resolved few days, if you could try again the program by doing a _pull_.

Thank you!

**Comment by tattiyaS** [comment]
thank you so much!
